[package]
name = "npdatetime-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "npdatetime"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
npdatetime_core = { package = "npdatetime", path = "../.." }

[build-dependencies]
