[package]
name = "npdatetime-python"
version = "0.1.10"
edition = "2021"

[lib]
name = "npdatetime_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.0", features = ["extension-module"] }
npdatetime_core = { package = "npdatetime", path = "../.." }

[build-dependencies]
